trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'HarshadAllwin1'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t weu24.azurecr.io/web-game:tag 2048-game
      az acr login -n weu24
      docker push weu24.azurecr.io/web-game:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'HarshadAllwin1'
    azureResourceGroup: 'weu-rg'
    kubernetesCluster: 'weu-k8s-cluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'HarshadAllwin1'
    azureContainerRegistry: 'weu24.azurecr.io'
    forceUpdate: false
